trigger: none
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployInfrastructure
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - script: |
      cd $(System.DefaultWorkingDirectory)/terraform
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
    env:
      ARM_CLIENT_ID: $(clientId)
      ARM_CLIENT_SECRET: $(clientSecret)
      ARM_SUBSCRIPTION_ID: $(subscriptionId)
      ARM_TENANT_ID: $(tenantId)
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform

- job: DeployMediaWiki
  dependsOn: DeployInfrastructure
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - script: |
      cd $(System.DefaultWorkingDirectory)/ansible
      ansible-playbook -i inventory.ini deploy_mediawiki.yml
    displayName: 'Execute Ansible Playbook'
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform
