trigger: none
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y python3-pip
      pip3 install --upgrade ansible
    displayName: 'Install Ansible'

  - script: |
      cd $(System.DefaultWorkingDirectory)/terraform
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Terraform Apply'

  - script: |
      cd $(System.DefaultWorkingDirectory)/ansible
      ansible-playbook -i inventory.ini deploy_mediawiki.yml
    displayName: 'Run Ansible Playbook'

